### PR TITLE
action.html: Hide inlines

### PR DESCRIPTION
**Pull request by jayvdb**
Fixes https://github.com/jyveapp/django-action-framework/issues/13

### CODE REVIEW

**Comment by tomage** [comment]
@jayvdb  - before I merge this in - would you mind updating your commit message so it conforms to this? https://github.com/jyveapp/django-action-framework/blob/master/CONTRIBUTING.rst#releases-and-versioning

You can try and use `git-tidy` (https://pypi.org/project/git-tidy/), but you can also just add the trailer manually.

Your commit message would then look something like this:

```
action.html: Hide inlines

Type: bug
```

If "bug" is in fact the correct type. There's a list of types found here: https://github.com/jyveapp/django-action-framework/blob/master/.git-tidy/commit.yaml .

**Review by tomage — APPROVED** [review]
Not being too familiar with the issue at hand (I read over the discussion between Josh and you), but this seems to do the trick.

Approving - but I'll wait for commit message to include the header as per https://github.com/jyveapp/django-action-framework/pull/16#issuecomment-701562125.

Many thanks for sending over this (and the other) PR, and sorry for the late reply on both of them - we've gotta adjust notifications on these so the team here at Jyve gets notified on these ASAP.

**Comment by jayvdb** [comment]
The commit template doesnt describe how to link to the issue being fixed.
So my commit message may not yet be to your liking, and I am happy to improve it again once this is clarified.

**Comment by tomage** [comment]
> The commit template doesnt describe how to link to the issue being fixed.
> So my commit message may not yet be to your liking, and I am happy to improve it again once this is clarified.

Oh I see. Yeah - we haven't (yet) started to put in links to GitHub issues in there (yet). As it happens, having that extra git-trailer doesn't bug the `git-tidy-lint` command, so it should be good! I'll merge as-is.

**Pull request merged**
